-- MySQL Script generated by MySQL Workbench
-- Mon Nov 14 20:28:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `divicuentas2` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `divicuentas2`  ;
USE `divicuentas2`;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Usuario` (
  `Celular` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `NickName` VARCHAR(45) NULL,
  `Pais` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`Celular`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Grupo` (
  `idGrupo` INT NOT NULL,
  `NombreGrupo` VARCHAR(45) NULL,
  `DescripcionGrupo` VARCHAR(45) NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsuariosDelGrupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`UsuariosDelGrupo` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`UsuariosDelGrupo` (
  `Grupo_idGrupo` INT NOT NULL,
  `Usuario_Celular` INT NOT NULL,
  PRIMARY KEY (`Grupo_idGrupo`, `Usuario_Celular`),
  INDEX `fk_Grupo_has_Usuario_Usuario1_idx` (`Usuario_Celular` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Usuario_Grupo_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Usuario_Grupo`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_Celular`)
    REFERENCES `mydb`.`Usuario` (`Celular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Cuenta` (
  `idCuenta` INT NOT NULL,
  `Nombre_Cuenta` VARCHAR(45) NULL,
  `Fecha_Cuenta` DATE NULL,
  `divisa` VARCHAR(45) NULL,
  `Cuentacol` VARCHAR(45) NULL,
  `Total_Cuenta` VARCHAR(45) NULL,
  `Nombre_Actividad` VARCHAR(45) NULL,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario_Parte_Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Usuario_Parte_Cuenta` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Usuario_Parte_Cuenta` (
  `Cuenta_idCuenta` INT NOT NULL,
  `Usuario_Celular` INT NOT NULL,
  `Monto_persona` INT NULL,
  PRIMARY KEY (`Cuenta_idCuenta`, `Usuario_Celular`),
  INDEX `fk_Cuenta_has_Usuario_Usuario1_idx` (`Usuario_Celular` ASC) VISIBLE,
  INDEX `fk_Cuenta_has_Usuario_Cuenta1_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_has_Usuario_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cuenta_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_Celular`)
    REFERENCES `mydb`.`Usuario` (`Celular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Saldo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Saldo` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Saldo` (
  `idSaldo` INT NOT NULL,
  `Afavor` TINYINT NULL,
  `Valor` DOUBLE NULL,
  PRIMARY KEY (`idSaldo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Deuda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Deuda` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Deuda` (
  `Saldo_idSaldo` INT NOT NULL,
  `Usuario_Celular` INT NOT NULL,
  `Celular_amigo` VARCHAR(45) NULL,
  `NickNameAmigo` VARCHAR(45) NULL,
  PRIMARY KEY (`Saldo_idSaldo`, `Usuario_Celular`),
  INDEX `fk_Saldo_has_Usuario_Usuario1_idx` (`Usuario_Celular` ASC) VISIBLE,
  INDEX `fk_Saldo_has_Usuario_Saldo1_idx` (`Saldo_idSaldo` ASC) VISIBLE,
  CONSTRAINT `fk_Saldo_has_Usuario_Saldo1`
    FOREIGN KEY (`Saldo_idSaldo`)
    REFERENCES `mydb`.`Saldo` (`idSaldo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Saldo_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_Celular`)
    REFERENCES `mydb`.`Usuario` (`Celular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Borrador_cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Borrador_cuenta` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Borrador_cuenta` (
  `Grupo_idGrupo` INT NOT NULL,
  `Saldo_idSaldo` INT NOT NULL,
  `Nombre_borrador` VARCHAR(45) NULL,
  `Fecha_borrador` VARCHAR(45) NULL,
  `Divisa_borrador` VARCHAR(45) NULL,
  `Total_borrador` VARCHAR(45) NULL,
  PRIMARY KEY (`Grupo_idGrupo`, `Saldo_idSaldo`),
  INDEX `fk_Grupo_has_Saldo_Saldo1_idx` (`Saldo_idSaldo` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Saldo_Grupo1_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Saldo_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `mydb`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Saldo_Saldo1`
    FOREIGN KEY (`Saldo_idSaldo`)
    REFERENCES `mydb`.`Saldo` (`idSaldo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `divicuentas2`.`Notificacion` ;

CREATE TABLE IF NOT EXISTS `divicuentas2`.`Notificacion` (
  `Deuda_Saldo_idSaldo` INT NOT NULL,
  `Deuda_Usuario_Celular` INT NOT NULL,
  `Usuario_Celular` INT NOT NULL,
  `Mensaje_notificacion` VARCHAR(45) NULL,
  `Estado_Aceptacion` VARCHAR(45) NULL,
  PRIMARY KEY (`Deuda_Saldo_idSaldo`, `Deuda_Usuario_Celular`, `Usuario_Celular`),
  INDEX `fk_Deuda_has_Usuario_Usuario1_idx` (`Usuario_Celular` ASC) VISIBLE,
  INDEX `fk_Deuda_has_Usuario_Deuda1_idx` (`Deuda_Saldo_idSaldo` ASC, `Deuda_Usuario_Celular` ASC) VISIBLE,
  CONSTRAINT `fk_Deuda_has_Usuario_Deuda1`
    FOREIGN KEY (`Deuda_Saldo_idSaldo` , `Deuda_Usuario_Celular`)
    REFERENCES `mydb`.`Deuda` (`Saldo_idSaldo` , `Usuario_Celular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Deuda_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_Celular`)
    REFERENCES `mydb`.`Usuario` (`Celular`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Insertar Usuarios 

INSERT INTO Usuario VALUES (3005270124, "Manuel", "Muelas","Colombia","Mnanuel@@asd.com","123456");
INSERT INTO Usuario VALUES (3001230122, "Juan", "juni","Colombia","Juanl@@asd.com","123456");
INSERT INTO Usuario VALUES (3005670124, "Venus", "jupi","Colombia","Venus@asd.com","123456");
INSERT INTO Usuario VALUES (3005370124, "Wilches", "wil","Colombia","Wilches@asd.com","123456");
INSERT INTO Usuario VALUES (3005570121, "Laura", "lau","Colombia","aura@asd.com","123456");
INSERT INTO Usuario VALUES (3012370122, "Juan pablo", "JuanPa","Colombia","Juan pablo@asd.com","123456");
INSERT INTO Usuario VALUES (3012567012, "Roddrigo", "Rodd","Colombia","Roddrigo@asd.com","123456");

-- Insertar Grupos
Insert into Grupo Values(123, "Panas U", "Para salir a comer cosas");

-- Insertar Personas al Grupo
Insert into UsuariosDelGrupo values(123,3005270124);
Insert into UsuariosDelGrupo values(123,3001230122);
Insert into UsuariosDelGrupo values(123,3005670124);
Insert into UsuariosDelGrupo values(123,3005370124);
Insert into UsuariosDelGrupo values(123,3012567012);
  